### PR TITLE
NZ is sticking around for randoms

### PR DESCRIPTION
**Pull request by kylesza**

### CODE REVIEW

**Comment by nickcharles** [comment]
Each one of the arrays (is that what they are?) has a comma at the very end, from what I understand this breaks them? Those commas are both in the sound arrays and the command arrays.

**Comment by kylesza** [comment]
No, I noticed all the original sounds have that as well. What was breaking them was the converter erring out and creating 0kb .dca files. I deleted or fixed the ones that this happened too

**Comment by kylesza** [comment]
Just trust me on this one, these sounds are fire.

**Comment by nickcharles** [comment]
In the future we definitely should not have PRs with 73 files changes but...that's the future.

**Pull request merged**
